"""add additional columns to eventregistration

Revision ID: 59125f0cc86c
Revises: 
Create Date: 2024-10-08 06:36:36.822467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59125f0cc86c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RegisteredDate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('Country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('PhoneNumber', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('DateOfBirth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('Gender', sa.String(length=10), nullable=True))
        batch_op.drop_column('RegistrationDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RegistrationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('Gender')
        batch_op.drop_column('DateOfBirth')
        batch_op.drop_column('PhoneNumber')
        batch_op.drop_column('Country')
        batch_op.drop_column('RegisteredDate')

    op.create_table('user',
    sa.Column('userid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('teamid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teamid'], ['team.teamid'], name='user_teamid_fkey'),
    sa.PrimaryKeyConstraint('userid', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    # ### end Alembic commands ###
